# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8caed756c8baee47ebcb7f4e7811ecc2ae131ba33602ce0ad5e6728ce57788700cf784effde71e157724fbe6d54e67b4f425edc503301d2d1ddbeef8185c6048

test:
  secret_key_base: f6e0b98accf50754af32dd8ab3d0da36d0a82ccf1476b9ddd795b1a980fca34a072089f7b99ed774211f2835cbbdff344efdd4eb6d2cbc2a0d6f6839f3cdc063

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
